#include <exception>
#include <iostream>

class Test {
 public:
  int * ptr;
  Test() : ptr(new int[4]) { throw std::exception(); }

  ~Test() {
    std::cout << "~Test() is called" << std::endl;
    delete[] ptr;
  }
};

int main() {
  Test t;
}
